POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

# ###

# POST http://localhost:3000/accounts HTTP/1.1
# Content-Type: application/json

# {
#     "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
# }

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "f5fd4921-412e-4550-b6f0-2a0e8db728a1",
    "account_id_to": "e640ab99-e863-497d-b464-5eebbf65ebe4",
    "amount": 1
}

###

GET http://localhost:3003/balances/f5fd4921-412e-4550-b6f0-2a0e8db728a1 HTTP/1.1

###

GET http://localhost:3003/balances/e640ab99-e863-497d-b464-5eebbf65ebe4 HTTP/1.1